name: Feature Tests

on:
  workflow_call:

env:
  RAILS_ENV: test
  BUNDLE_PATH_RELATIVE_TO_CWD: true
  AVO_LICENSE_KEY: license_123
  BUNDLE_RUBYGEMS__PKG__GITHUB__COM: adrianthedev:${{secrets.GH_REGISTRY_AVO_FILTERS_TOKEN}}

jobs:
  feature_specs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler: default
        ruby-version: 3.2.0

    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-test-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-test-gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Setup DB
      run: bin/rails db:setup

    - name: Get yarn cache directory path
      id: test-yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: test-yarn-cache
      with:
        path: ${{ steps.test-yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-test-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-test-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Yarn install the dummy app
      run: |
        cd spec/dummy
        yarn

    - name: Yarn install
      run: yarn

    - name: Build assets
      run: yarn build

    - name: Run tests
      id: run_tests
      run: bundle exec rspec spec/features

    - uses: actions/upload-artifact@v3
      if: always() && steps.run_tests.outcome == 'failure'
      with:
        name: rspec_failed_screenshots_rails
        path: ./spec/dummy/tmp/screenshots
