name: PR Labeler

on:
  workflow_call:

jobs:
  pr-labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
