name: Lint

on:
  workflow_call:

jobs:
  standardrb:
    name: runner / standardrb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: standardrb
        uses: adrianthedev/action-standardrb@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          rubocop_version: 0.1.6
          rubocop_flags: --format progress

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check for eslint config
        run: |
          pwd
          if [ ! -f .eslintrc.json ]; then
            echo "File not found!"
            exit 0
          fi
      - run: yarn
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
