name: Lint

on:
  workflow_call:

jobs:
  standardrb:
    name: runner / standardrb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          ruby-version: 3.3.0

      - name: standardrb
        uses: avo-hq/action-standardrb@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          rubocop_version: 1.33.0
          rubocop_flags: --format progress

  erb-lint:
    name: runner / erb-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: erb-lint
        uses: reviewdog/action-erblint@v1
        with:
          github_token: ${{ secrets.github_token }}

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check for eslint config
        run: |
          pwd
          if [ ! -f .eslintrc.json ]; then
            echo "File not found!"
            exit 0
          fi
      - run: yarn add global eslint@6.8.0 eslint-plugin-sort-imports-es6-autofix@^0.5.0 eslint-config-airbnb@^18.1.0 eslint-config-airbnb-base@^14.1.0 babel-eslint@^10.1.0 eslint-plugin-import@^2.20.2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
