name: Build, Generate Ruby Gem and Release

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install axios
      run: npm i -g axios

    - name: Get gem version
      id: gem_version
      run: |
        echo "::set-output name=tag::$(sed "s|refs/tags/v||" <<< ${{ github.ref }})"

    - name: Get release notes
      id: get_release_notes
      run: |
        echo "::set-output name=release_notes::$(node .github/get-release-notes-from-draft.js ${{github.repository}} ${{secrets.GITHUB_TOKEN}})"

    - name: Create Release
      id: create_release
      if: ${{steps.get_release_notes.outputs.release_notes != ''}}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{fromJson(steps.get_release_notes.outputs.release_notes)}}
        draft: false
        prerelease: false

    - name: Publish release on avohq.io
      run: curl https://avohq.io/releases/refresh_releases
